# Use this notebook for your 3 choices of APIs

In [1]:
import json
import requests
import pandas as pd

In [2]:
#1. Cat Facts

response = requests.get('https://cat-fact.herokuapp.com/facts/random?animal_type=cat&amount=50')
response
data = pd.DataFrame(response.json())
data.head()

,status,_id,user,text,type,deleted,createdAt,updatedAt,__v,source,used
0,"{'verified': None, 'sentCount': 0}",6404b3ef7ef7aa816f4b0f91,63fb7e70fcf661e5a0978c99,"""About half of the cats in the world respond t...",cat,False,2023-03-05T15:23:27.060Z,2023-03-05T15:23:27.060Z,0,NaN,NaN
1,"{'verified': None, 'sentCount': 0}",65bd2fd0d75d61070dd12647,65bd24e7d75d61070dd1192d,This is the best gaming accessory under £5.,cat,False,2024-02-02T18:09:20.985Z,2024-02-02T18:09:20.985Z,0,NaN,NaN
2,"{'verified': None, 'sentCount': 0}",6266bbabcdcef2bc79a439dc,6261902419ffd4911838b6ed,Cats like watch football by TV.,cat,False,2022-04-25T15:18:03.381Z,2022-04-25T15:18:03.381Z,0,NaN,NaN
3,"{'verified': None, 'sentCount': 0}",6404f35febdaaca99be58bc6,63fb745efcf661e5a0978073,You need cat?.,cat,False,2023-03-05T19:54:07.896Z,2023-03-05T19:54:07.896Z,0,NaN,NaN
4,"{'verified': None, 'sentCount': 0}",62483a93a2d23ebaf5d610ae,61b11802f9c77cdad2d21bd3,Lowwwww.,cat,False,2022-04-02T11:59:15.818Z,2022-04-02T11:59:15.818Z,0,NaN,NaN

In [4]:
data[['text']]

                                                 text
0   "About half of the cats in the world respond t...
1         This is the best gaming accessory under £5.
2                     Cats like watch football by TV.
3                                      You need cat?.
4                                            Lowwwww.
5                                              45456.
6                         Дурацкие факты о котах :)).
7                         Cats can drink ocean water.
8                                           (!#)%^&*.
9                                    Привет, кошаки!.
10                   Hello does anyone want to talk?.
11                                                21.
12  Lorem ipsum dolor sit amet, consectetuer adipi...
13                    Кошки - очень вредные создания.
14                                                 2.
15                                  Avxcv, svzv,svcv.
16                                       Авторизация.
17                              Third fact about cat.
18                         New fact 4rd of April 2.0.
19                                         Back-mood.
20  A tiger's stripes are like fingerprints; no tw...
21  The pattern on the nose of each cat is unique,...
22   Cat is more clever and kind animal in the world.
23                      Cats are kind but not always.
24                              Коты очень милые 234.
25                           Cats are not colorblind.
26                                           Приqtwe.
27  Если кошка стоит около вас с поднятым хвостом ...
28                                            Fact_7.
29                                       Raz dwa tri.
30                               Cats like mushrooms.
31                        Josephine was a sweet girl.
32                            Cats are really cool!!.
33                                    They love kids.
34                                     Привет котики.
35  Most breeds of cat have a noted fondness for s...
36                                          Fghfhgf1.
37                         """"""""""""""""""""""""".
38                              Cats never worry gfd.
39                                               Pop.
40                                   Sssssssssssssss.
41  Intolerant, and milk can cause painful stomach...
42                                            Asdasd.
43  Cats lick themselves to stop smelling like hum...
44  The average lifespan of an outdoor-only (feral...
45                                         TestFacts.
46                         Add new fact about my cat.
47                                        Memory one.
48                                            Fact_2.
49  Cats are Nearsighted, but See Great in the Dark1.

In [ ]:
# You can see that people put a lot of junk in there, too. But there still are some cat facts in here. I guess before you want to use the data you have to clean it.
# It was just a fun start. I do not really see a project here.

In [5]:
#2. Crypto Currency

response = requests.get('https://api.coincap.io/v2/assets')
data = pd.DataFrame(response.json())
data

                                                 data      timestamp
0   {'id': 'bitcoin', 'rank': '1', 'symbol': 'BTC'...  1715086697124
1   {'id': 'ethereum', 'rank': '2', 'symbol': 'ETH...  1715086697124
2   {'id': 'tether', 'rank': '3', 'symbol': 'USDT'...  1715086697124
3   {'id': 'binance-coin', 'rank': '4', 'symbol': ...  1715086697124
4   {'id': 'solana', 'rank': '5', 'symbol': 'SOL',...  1715086697124
..                                                ...            ...
95  {'id': 'xinfin-network', 'rank': '96', 'symbol...  1715086697124
96  {'id': 'celo', 'rank': '97', 'symbol': 'CELO',...  1715086697124
97  {'id': 'ravencoin', 'rank': '98', 'symbol': 'R...  1715086697124
98  {'id': 'zilliqa', 'rank': '99', 'symbol': 'ZIL...  1715086697124
99  {'id': '0x', 'rank': '100', 'symbol': 'ZRX', '...  1715086697124

[100 rows x 2 columns]

In [6]:
from pandas import json_normalize 

results = response.json()
flattened_data = json_normalize(results["data"])
flattened_data

,id,rank,symbol,name,supply,maxSupply,marketCapUsd,volumeUsd24Hr,priceUsd,changePercent24Hr,vwap24Hr,explorer
0,bitcoin,1,BTC,Bitcoin,19695100.0000000000000000,21000000.0000000000000000,1253914552663.2325973479439000,7393524586.4447164063886608,63666.3206921128908890,0.2506149446486314,63642.8496390228682392,https://blockchain.info/
1,ethereum,2,ETH,Ethereum,120101536.9316922100000000,None,369645293928.4618748705142520,4502919916.5316097530074193,3077.7732189946724960,-0.6558032816553038,3087.0993690086035752,https://etherscan.io/
2,tether,3,USDT,Tether,110971000757.3761600000000000,None,110981950617.1542877747897261,15649077170.2084745889588498,1.0000986731641906,0.0160529506393612,1.0002388637965894,https://www.omniexplorer.info/asset/31
3,binance-coin,4,BNB,BNB,166801148.0000000000000000,166801148.0000000000000000,98816101833.7477599203504040,304737933.3992700790277137,592.4185955467630230,1.1919216060535464,589.6646952253634941,https://etherscan.io/token/0xB8c77482e45F1F44d...
4,solana,5,SOL,Solana,447983883.1770181000000000,None,69596929760.5135295317013029,1007619712.2015747986974836,155.3558785797049022,2.8956657578667816,154.2555660752451419,https://explorer.solana.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,xinfin-network,96,XDC,XinFin Network,12293293518.5500000000000000,None,432434146.5041042184753085,2222679.3492255118812284,0.0351764273627390,6.5176875728495433,0.0366185213352457,https://etherscan.io/token/0x41ab1b6fcbb2fa9dc...
96,celo,97,CELO,Celo,536677480.0000000000000000,1000000000.0000000000000000,429649226.2275479216929480,4064856.2234701373357027,0.8005724895099901,-1.3198180440769787,0.8046106742265359,https://explorer.celo.org/blocks
97,ravencoin,98,RVN,Ravencoin,13813466201.6639180000000000,21000000000.0000000000000000,421731861.1655568189537516,30742722.6496920215294858,0.0305304877869652,-2.7918197748953027,0.0304863325684519,https://ravencoin.network/
98,zilliqa,99,ZIL,Zilliqa,17372203179.0000000000000000,21000000000.0000000000000000,421003265.0457668535503952,8556359.5348398287465200,0.0242343046939888,-0.6024717278178148,0.0242872743134587,https://etherscan.io/token/0x05f4a42e251f2d52b...
99,0x,100,ZRX,0x Protocol,847496054.8027713000000000,1000000000.0000000000000000,420543270.0836022157419548,7996530.4430531237269352,0.4962185578332524,0.6345744911661045,0.4928125701575763,https://etherscan.io/token/ZRX

In [ ]:
# There is the possibility to get historical data, too. For a project you could analyze the correlation between different crypto currencies and check for certain events to figure out what drives the prices.

In [12]:
# 3. Open Food Facts
#https://openfoodfacts.github.io/openfoodfacts-server/api/tutorial-off-api/

response = requests.get('https://world.openfoodfacts.net/api/v2/product/3017624010701?fields=product_name,nutriscore_data')

results = response.json()
data = pd.DataFrame(results)
data

,code,product,status,status_verbose
nutriscore_data,3017624010701,"{'energy': 2255, 'energy_points': 6, 'energy_v...",1,product found
product_name,3017624010701,Nutella,1,product found

In [13]:
results = response.json()
flattened_data = json_normalize(results["product"])
flattened_data

,product_name,nutriscore_data.energy,nutriscore_data.energy_points,nutriscore_data.energy_value,nutriscore_data.fiber,nutriscore_data.fiber_points,nutriscore_data.fiber_value,nutriscore_data.fruits_vegetables_nuts_colza_walnut_olive_oils,nutriscore_data.fruits_vegetables_nuts_colza_walnut_olive_oils_points,nutriscore_data.fruits_vegetables_nuts_colza_walnut_olive_oils_value,...,nutriscore_data.saturated_fat,nutriscore_data.saturated_fat_points,nutriscore_data.saturated_fat_value,nutriscore_data.score,nutriscore_data.sodium,nutriscore_data.sodium_points,nutriscore_data.sodium_value,nutriscore_data.sugars,nutriscore_data.sugars_points,nutriscore_data.sugars_value
0,Nutella,2255,6,2255,0,0,0,10.714286,0,10.7,...,10.6,10,10.6,26,43,0,43,56.3,10,56.3

In [ ]:
# You can also get a list of foods for example Orange Juices with a special rating. Then you could use the product code to get the details of each product as seen above.

In [14]:
response = requests.get('https://world.openfoodfacts.net/api/v2/search?categories_tags_en=Orange Juice&nutrition_grades_tags=c&fields=code,nutrition_grades,categories_tags_en')
data = pd.DataFrame(response.json())
data

,count,page,page_count,page_size,products,skip
0,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
1,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
2,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
3,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
4,1875,1,24,24,{'categories_tags_en': ['Beverages and beverag...,0
5,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
6,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
7,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
8,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
9,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
10,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
11,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
12,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
13,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
14,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
15,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
16,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
17,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
18,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
19,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
20,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
21,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
22,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0
23,1875,1,24,24,{'categories_tags_en': ['Plant-based foods and...,0

In [15]:
results = response.json()
flattened_data = json_normalize(results["products"])
flattened_data

,categories_tags_en,code,nutrition_grades
0,"[Plant-based foods and beverages, Beverages, P...",3502110009449,c
1,"[Plant-based foods and beverages, Beverages, P...",3502110006790,c
2,"[Plant-based foods and beverages, Beverages, P...",3123349011227,c
3,"[Plant-based foods and beverages, Beverages, P...",3502110009401,c
4,"[Beverages and beverages preparations, Plant-b...",3045320104127,c
5,"[Plant-based foods and beverages, Beverages, P...",3123349014129,c
6,"[Plant-based foods and beverages, Beverages, P...",5038862160506,c
7,"[Plant-based foods and beverages, Beverages, P...",4056489258292,c
8,"[Plant-based foods and beverages, Beverages, P...",3608580844136,c
9,"[Plant-based foods and beverages, Beverages, P...",3564700494493,c
10,"[Plant-based foods and beverages, Beverages, P...",3250390001287,c
11,"[Plant-based foods and beverages, Beverages, P...",5449000257789,c
12,"[Plant-based foods and beverages, Beverages, P...",3560070478637,c
13,"[Plant-based foods and beverages, Beverages, P...",3245412373039,c
14,"[Plant-based foods and beverages, Beverages, P...",3123340008288,c
15,"[Plant-based foods and beverages, Beverages, P...",4056489236931,c
16,"[Plant-based foods and beverages, Beverages, P...",3564707079884,c
17,"[Plant-based foods and beverages, Beverages, P...",3270190192794,c
18,"[Plant-based foods and beverages, Beverages, P...",5038862133838,c
19,"[Plant-based foods and beverages, Beverages, P...",3564700002841,c
20,"[Plant-based foods and beverages, Beverages, P...",3502110005243,c
21,"[Plant-based foods and beverages, Beverages, P...",3560070820542,c
22,"[Plant-based foods and beverages, Beverages, P...",3560070167470,c
23,"[Plant-based foods and beverages, Beverages, P...",4048517701818,c

In [16]:
flattened_data['categories_tags_en'][0]

['Plant-based foods and beverages',
 'Beverages',
 'Plant-based beverages',
 'Fruit-based beverages',
 'Juices and nectars',
 'Fruit juices',
 'Non-alcoholic beverages',
 'Orange juices',
 'Squeezed juices',
 'Orange juices without pulp',
 'Squeezed orange juices']